// Package sharpdpapicases exports the canonical ParityCase slice for
// SharpDPAPI parity tests.
//
// Every case is a real attacker invocation backed by harmj0y's "Operational
// Guidance for Offensive Use of SharpDPAPI" blog series + the GhostPack
// README. Goldens are captured from the NATIVE SharpDPAPI.exe (Flangvik/
// SharpCollection precompiled) on the GOAD Win11 worker.
package sharpdpapicases

import (
	"time"

	"github.com/praetorian-inc/wftest/parity/labctl"
)

// Cases returns the SharpDPAPI parity invocations. Lab artifacts:
//   - scripts/lab-setup/sharpdpapi-plant.ps1 plants a DPAPI blob, an
//     RDG file, an imported cert with private key, and cmdkey
//     credential manager entries on win11-domainuser's profile.
func Cases() []labctl.ParityCase {
	const localT = 120 * time.Second
	const elevatedT = 180 * time.Second

	return []labctl.ParityCase{
		// User-scope verbs — run as the planted user, picks up the
		// interactive logon master key automatically.
		{Name: "triage", Args: []string{"triage"}, Persona: "win11-domainuser", Timeout: localT},
		{Name: "masterkeys", Args: []string{"masterkeys"}, Persona: "win11-domainuser", Timeout: localT},
		{Name: "credentials", Args: []string{"credentials"}, Persona: "win11-domainuser", Timeout: localT},
		{Name: "vaults", Args: []string{"vaults"}, Persona: "win11-domainuser", Timeout: localT},
		{Name: "rdg", Args: []string{"rdg"}, Persona: "win11-domainuser", Timeout: localT},
		{Name: "certificates", Args: []string{"certificates"}, Persona: "win11-domainuser", Timeout: localT},

		// Machine-scope verbs — require SYSTEM impersonation. Run as
		// localuser (local admin) so the SYSTEM token-duplication path
		// is available.
		{Name: "machinetriage", Args: []string{"machinetriage"}, Timeout: elevatedT},
		{Name: "machinemasterkeys", Args: []string{"machinemasterkeys"}, Timeout: elevatedT},
		{Name: "machinecredentials", Args: []string{"machinecredentials"}, Timeout: elevatedT},
		{Name: "machinevaults", Args: []string{"machinevaults"}, Timeout: elevatedT},
		{Name: "sccm", Args: []string{"sccm"}, Timeout: elevatedT},

		// Blob describe — operates on a base64-encoded DPAPI blob
		// generated by the plant script and dropped into a known path.
		{
			Name: "blob",
			// /target:C:\WfLab\dpapi-sample.blob is a binary file containing a
			// real DPAPI blob created by ProtectedData.Protect(CurrentUser).
			Args:    []string{"blob", "/target:C:\\WfLab\\dpapi-sample.blob"},
			Persona: "win11-domainuser",
			Timeout: localT,
		},

		// Registry blob search — walks HKLM/HKCU for DPAPI blob values.
		{Name: "search", Args: []string{"search", "/type:registry"}, Persona: "win11-domainuser", Timeout: localT},

		// Domain backup key retrieval — requires DA token.
		{Name: "backupkey", Args: []string{"backupkey"}, Persona: "win11-domainadmin", Timeout: elevatedT},
	}
}
