package patch

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// dllImportRe captures the DLL name from `[DllImport("<dll>", ...)` attributes.
// We accept a single- or double-quoted name with optional path separators (some
// declarations name "advapi32.dll" while others name just "advapi32"). The
// regex is intentionally lax on the trailing parameters (CharSet, CallingConvention,
// SetLastError, etc.) — we only need the DLL identifier.
var dllImportRe = regexp.MustCompile(`\[DllImport\s*\(\s*"([^"]+)"`)

// pinvokeFnRe captures the C# method name immediately following a [DllImport]
// attribute. We anchor on the typical NativeAOT-WASI declaration shape:
//
//	[DllImport(...)]
//	[other attrs]*
//	private/internal/public static extern <returnType> FunctionName(...
//
// The regex must skip over additional attributes (MarshalAs, SuppressUnmanaged…)
// between the DllImport line and the extern signature.
var pinvokeFnRe = regexp.MustCompile(
	`\[DllImport\s*\(\s*"([^"]+)"[^\]]*\][^;]*?\bextern\s+[^()]*?\s(\w+)\s*\(`)

// DiscoveredPInvoke describes a single [DllImport] declaration found in
// the source tree. The Function is the C# method name; DLL is exactly as
// written in the attribute (with or without the .dll suffix).
type DiscoveredPInvoke struct {
	DLL      string
	Function string
	File     string // relative to srcDir, for diagnostics
}

// EmitDirectPInvokeProps walks srcDir for .cs files, finds every [DllImport]
// declaration, and writes Properties/WfDirectPInvoke.props with one
// <DirectPInvoke Include="dll" /> entry per unique DLL.
//
// NativeAOT-LLVM requires every P/Invoke target to be statically resolvable
// at link time (the runtime throws PlatformNotSupportedException with the
// message "Lazy PInvoke resolution is not supported when targeting
// WebAssembly" if a DllImport falls through to dynamic resolution). The
// DirectPInvoke entry tells the linker to look for an externally-defined
// symbol named "<dll-prefix>_<FunctionName>" rather than generating a
// dynamic resolution call. When that symbol exists in our bridge code
// (dotnet/bridge/pinvoke_nativeaot.c) the function works; when it doesn't,
// wasm-ld emits a clear "undefined symbol" error pointing at the exact
// function that needs a bridge stub — vastly more actionable than the
// runtime PNS exception.
//
// Returns the relative path of the props file (for callers that wire it
// into a csproj template) and the list of unique DLL names discovered.
func EmitDirectPInvokeProps(srcDir string, verbose bool) (string, []string, error) {
	discoveries, err := scanDllImports(srcDir)
	if err != nil {
		return "", nil, err
	}

	dllSet := map[string]bool{}
	for _, d := range discoveries {
		lower := strings.ToLower(d.DLL)
		if skipDllForDirectPInvoke(lower) {
			continue
		}
		// NativeAOT-LLVM DirectPInvoke matches case-sensitively against the
		// DllImport target. Tools mix cases (User32.dll, kernel32, Secur32.dll)
		// and the matcher won't normalize. Emit every distinct case spelling
		// we actually observed PLUS lowercase base/base+.dll defensively, so
		// any reasonable casing in source gets picked up.
		dllSet[d.DLL] = true
		baseLower := strings.TrimSuffix(lower, ".dll")
		dllSet[baseLower] = true
		dllSet[baseLower+".dll"] = true
	}

	dlls := make([]string, 0, len(dllSet))
	for d := range dllSet {
		dlls = append(dlls, d)
	}
	sort.Strings(dlls)

	relPath := filepath.Join("Properties", "WfDirectPInvoke.props")
	abs := filepath.Join(srcDir, relPath)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return "", nil, fmt.Errorf("creating Properties/: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="utf-8"?>
<!--
  WasmForge — DirectPInvoke registrations.

  Auto-generated by internal/patch/pinvoke_scanner.go. Do not edit by hand.

  NativeAOT-LLVM requires every P/Invoke target to be statically resolvable
  at link time. Each entry below tells the linker to look for an externally-
  defined symbol "<dll-prefix>_<FunctionName>" rather than generating a
  dynamic resolution stub. The bridge code in dotnet/bridge/pinvoke_nativeaot.c
  provides those symbols for the functions we've stubbed; missing symbols
  surface as actionable wasm-ld link errors.
-->
<Project>
  <ItemGroup>
`)
	for _, d := range dlls {
		fmt.Fprintf(&sb, "    <DirectPInvoke Include=%q />\n", d)
	}
	sb.WriteString(`  </ItemGroup>
</Project>
`)

	if err := os.WriteFile(abs, []byte(sb.String()), 0o644); err != nil {
		return "", nil, fmt.Errorf("writing %s: %w", abs, err)
	}

	if verbose {
		uniqueFns := map[string]bool{}
		for _, d := range discoveries {
			uniqueFns[d.DLL+":"+d.Function] = true
		}
		fmt.Fprintf(os.Stderr,
			"[pinvoke-scanner] wrote %s: %d unique DLLs, %d unique (dll,fn) pairs across %d declarations\n",
			relPath, len(dllSet)/2, len(uniqueFns), len(discoveries))
	}

	return relPath, dlls, nil
}

// skipDllForDirectPInvoke filters out attribute targets that aren't real
// Windows DLLs and would either confuse wasm-ld or duplicate hand-curated
// entries the csproj template already declares.
//
//   - "*"   is NativeAOT-LLVM's wildcard placeholder used by source generators
//     to declare "any unmanaged target". It is never a valid DirectPInvoke
//     entry — the linker treats it as a literal symbol-prefix of "*_".
//   - "env" is the WasmForge bridge import module name. The csproj template
//     lists it, but older migrated projects may not — emit it always so the
//     scanner is self-correcting. Duplicates in csproj are harmless.
//   - "" guards against malformed [DllImport("")] attributes that exist in
//     a handful of GhostPack files.
func skipDllForDirectPInvoke(lower string) bool {
	switch lower {
	case "", "*":
		return true
	}
	return false
}

// scanDllImports walks srcDir for .cs files and returns every [DllImport]
// declaration it finds. The implementation parses each file as a single
// string because attributes and signatures often span multiple lines.
func scanDllImports(srcDir string) ([]DiscoveredPInvoke, error) {
	var out []DiscoveredPInvoke
	err := filepath.WalkDir(srcDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil // best-effort: skip unreadable subdirs
		}
		if d.IsDir() {
			// Skip generated/output directories that often contain copies of
			// already-built artifacts and would inflate our results.
			name := d.Name()
			if name == "obj" || name == "bin" || name == "node_modules" || name == ".git" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".cs") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(srcDir, path)
		content := string(data)

		// Primary match: full DllImport+extern declaration with the function
		// name captured. This is the data point bridge authors actually need.
		for _, m := range pinvokeFnRe.FindAllStringSubmatch(content, -1) {
			out = append(out, DiscoveredPInvoke{
				DLL:      m[1],
				Function: m[2],
				File:     rel,
			})
		}

		// Secondary fallback: capture standalone DllImport attributes that
		// the primary regex missed (unusual attribute layouts, comments
		// between attribute and signature, etc.). Function is unknown so
		// only the DLL contributes to the dedup set, but it still ensures
		// every DLL referenced anywhere in the source gets a DirectPInvoke
		// entry.
		for _, m := range dllImportRe.FindAllStringSubmatch(content, -1) {
			dll := m[1]
			// Skip if we already have a matching DLL+function entry from
			// the primary regex.
			alreadySeen := false
			for _, d := range out {
				if d.File == rel && d.DLL == dll {
					alreadySeen = true
					break
				}
			}
			if !alreadySeen {
				out = append(out, DiscoveredPInvoke{
					DLL:      dll,
					Function: "",
					File:     rel,
				})
			}
		}
		return nil
	})
	if err != nil {
		return out, fmt.Errorf("walking %s: %w", srcDir, err)
	}
	return out, nil
}
