package patch

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// EmitWfPreserveRdXml writes a NativeAOT Runtime-Directives file at
// <srcDir>/Properties/WfPreserve.rd.xml.
//
// Why per-Type entries (not just per-Assembly):
//
// NativeAOT-LLVM's `<Assembly Name="X" Dynamic="Required All" />` directive
// is enough for many reflection use cases, but it does NOT preserve
// getter-only auto-properties (`public object Foo { get; }`) under trim.
// Tools like Seatbelt's DefaultTextFormatter reflect over CommandDTOBase
// subclasses via `type.GetProperties()`; when those DTOs use the getter-only
// shape (AntiVirusDTO, WMIEventConsumerDTO, RegistryValueDTO, etc.) the
// reflection walk returns zero properties and the formatter prints empty
// rows. Evidence captured in `test/wmi-harness/` proves type-level
// `<Type Name="Foo.Bar" Dynamic="Required All" />` DOES preserve them.
//
// To avoid playing whack-a-mole per DTO, we emit one `<Type>` entry per
// class declared anywhere in the source tree. This is over-broad on
// purpose: the only downside is rd.xml verbosity (~hundreds of lines for
// a tool like Seatbelt), and trim already had `Required All` on the
// assembly so we're not preserving anything new at the assembly level —
// we're just upgrading the per-type guarantee from "best-effort" to
// "explicit." Stubs and System.Security.Principal.Windows keep the
// existing assembly-level entries.
func EmitWfPreserveRdXml(srcDir string, verbose bool) (string, error) {
	relPath := filepath.Join("Properties", "WfPreserve.rd.xml")
	abs := filepath.Join(srcDir, relPath)

	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return "", fmt.Errorf("creating Properties/: %w", err)
	}

	stubAssemblies, err := discoverStubAssemblies(srcDir)
	if err != nil && verbose {
		fmt.Fprintf(os.Stderr, "[rdxml] stub discovery: %v (continuing)\n", err)
	}

	mainAssembly := discoverMainAssembly(srcDir)
	classes := discoverAllClasses(srcDir)

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="utf-8"?>
<!--
  WasmForge — NativeAOT trim preservation directives.

  Auto-generated by internal/patch/rdxml.go. Do not edit by hand.

  Without this file, NativeAOT trim strips type/property metadata that the
  source tool relies on via Assembly.GetTypes() and Type.GetProperties().
  Per-Type Dynamic="Required All" entries are required for getter-only
  auto-properties (e.g. AntiVirusDTO.Engine) which assembly-level
  Required All does NOT preserve under NativeAOT-LLVM. See rdxml.go.
-->
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
`)
	if mainAssembly != "" {
		if len(classes) > 0 {
			fmt.Fprintf(&sb, "    <Assembly Name=%q Dynamic=\"Required All\">\n", mainAssembly)
			for _, fqn := range classes {
				fmt.Fprintf(&sb, "      <Type Name=%q Dynamic=\"Required All\" />\n", fqn)
			}
			sb.WriteString("    </Assembly>\n")
		} else {
			fmt.Fprintf(&sb, "    <Assembly Name=%q Dynamic=\"Required All\" />\n", mainAssembly)
		}
	}

	for _, name := range stubAssemblies {
		fmt.Fprintf(&sb, "    <Assembly Name=%q Dynamic=\"Required All\" />\n", name)
	}

	sb.WriteString(`    <Assembly Name="System.Security.Principal.Windows" Dynamic="Required All" />
`)

	sb.WriteString(`  </Application>
</Directives>
`)

	if err := os.WriteFile(abs, []byte(sb.String()), 0o644); err != nil {
		return "", fmt.Errorf("writing %s: %w", abs, err)
	}

	if verbose {
		fmt.Fprintf(os.Stderr, "[rdxml] wrote %s (preserving %d stub assemblies, %d types)\n",
			relPath, len(stubAssemblies), len(classes))
	}

	return relPath, nil
}

// reNamespace matches `namespace Foo.Bar` declarations (block or file-scoped).
// Word-boundary anchored so it matches after `;`/`{` or at line start.
var reNamespace = regexp.MustCompile(`\bnamespace\s+([\w.]+)\s*[;{]`)

// reClassDecl matches class declarations anywhere they validly appear in
// C# source. Modifiers before `class` are absorbed; the captured group is
// the bare type name (generics like `<T>` are excluded — rd.xml's Name
// matches by simple name). The leading `\b` prevents matching inside
// identifiers like `classification` and inside type constraints like
// `where T : class` (which lack a following identifier).
//
// Examples it matches:
//
//	class Foo
//	public class Foo
//	internal sealed partial class Foo
//	public abstract class Foo : Base
//	public class Foo<T> : Base<T>
var reClassDecl = regexp.MustCompile(`\b(?:(?:public|internal|private|protected|static|sealed|abstract|partial|unsafe|new)\s+)*class\s+(\w+)`)

// discoverAllClasses walks srcDir for .cs files and returns sorted-unique
// fully-qualified class names. Top-level classes are emitted as
// `Namespace.Type`; nested classes use `+` separators
// (e.g. `Namespace.Outer+Inner`) to match the format ILCompiler's
// RdXmlRootProvider resolves. Brace depth tracking ensures nested-class
// declarations are correctly attributed to their enclosing types instead
// of being mis-namespaced at the top level (which causes
// TypeLoadException at NativeAOT compile time).
//
// Excludes: stubs/, bin/, obj/, .vs/ (build outputs and stub assemblies
// already covered by Assembly-level entries).
func discoverAllClasses(srcDir string) []string {
	seen := map[string]bool{}
	var classes []string

	_ = filepath.WalkDir(srcDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == "bin" || name == "obj" || name == ".vs" || name == "stubs" {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".cs") {
			return nil
		}
		base := filepath.Base(path)
		if base == "AssemblyInfo.cs" || strings.HasSuffix(base, ".g.cs") || strings.HasSuffix(base, ".g.i.cs") {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		for _, fqn := range extractClassFqnsFromSource(string(data)) {
			if !seen[fqn] {
				seen[fqn] = true
				classes = append(classes, fqn)
			}
		}
		return nil
	})

	sort.Strings(classes)
	return classes
}

// extractClassFqnsFromSource scans a single C# source file and returns the
// fully-qualified type names declared in it, tracking namespace and class
// nesting so inner classes are joined with `+` (the ILCompiler convention).
//
// Approach: a tiny linear scan over the comment-stripped source. We walk
// character by character tracking brace depth. When we see a `class Foo`
// token, we record the depth at which it was declared; when the NEXT `{`
// opens that class's body, we push (name, opening-depth) onto a stack.
// When `}` closes a scope at the matching depth, we pop. This avoids the
// pitfall of trying to disambiguate class-body braces from method-body
// braces at match time — the next `{` after a class declaration always
// opens the class body in valid C#.
func extractClassFqnsFromSource(rawSrc string) []string {
	src := stripCSharpComments(stripDebugConditionals(rawSrc))
	if !reNamespace.MatchString(src) {
		return nil
	}

	// Frame describes any scope that contributes to a class FQN: either a
	// namespace (block-scoped namespace) or a class. Both push onto the
	// same stack so brace-depth tracking handles both. File-scoped
	// namespaces (`namespace X;`) are tracked separately because they
	// have no closing brace.
	type frame struct {
		name      string
		isClass   bool
		openDepth int
	}
	var stack []frame
	// At most one pending decl can exist at a time in valid C# (a
	// namespace or class name whose opening `{` hasn't yet been consumed).
	var pendingClass, pendingNs string
	var fileScopedNs string
	depth := 0

	var fqns []string
	emit := func(name string) {
		var nsParts, clsParts []string
		for _, f := range stack {
			if f.isClass {
				clsParts = append(clsParts, f.name)
			} else {
				nsParts = append(nsParts, f.name)
			}
		}
		if fileScopedNs != "" {
			nsParts = append([]string{fileScopedNs}, nsParts...)
		}
		nsPath := strings.Join(nsParts, ".")
		clsParts = append(clsParts, name)
		clsPath := strings.Join(clsParts, "+")
		if nsPath == "" {
			fqns = append(fqns, clsPath)
		} else {
			fqns = append(fqns, nsPath+"."+clsPath)
		}
	}

	i := 0
	n := len(src)
	for i < n {
		c := src[i]
		switch c {
		case '{':
			switch {
			case pendingClass != "":
				stack = append(stack, frame{name: pendingClass, isClass: true, openDepth: depth})
				pendingClass = ""
			case pendingNs != "":
				stack = append(stack, frame{name: pendingNs, isClass: false, openDepth: depth})
				pendingNs = ""
			}
			depth++
			i++
		case '}':
			depth--
			if len(stack) > 0 && depth == stack[len(stack)-1].openDepth {
				stack = stack[:len(stack)-1]
			}
			i++
		default:
			// Namespace tokens must be tried BEFORE class tokens — the regex
			// for class would not match `namespace`, but we still want to
			// consume the full namespace declaration in one step.
			if name, end, blockScoped := matchNamespaceDecl(src, i); name != "" {
				if blockScoped {
					pendingNs = name
				} else if fileScopedNs == "" {
					fileScopedNs = name
				}
				i = end
				continue
			}
			if name, end := matchClassDecl(src, i); name != "" {
				emit(name)
				pendingClass = name
				i = end
				continue
			}
			i++
		}
	}
	return fqns
}

// matchNamespaceDecl returns (nsName, endPos, blockScoped) if src[start:]
// begins a `namespace …;` or `namespace … {` declaration, else ("", start, false).
// For block-scoped namespaces, endPos points AT the opening `{` so the main
// loop's `{` handler can consume it and push the pendingNs onto the stack
// (consistent with how class declarations are handled). For file-scoped
// namespaces, endPos points past the closing `;`.
func matchNamespaceDecl(src string, start int) (string, int, bool) {
	if start > 0 {
		prev := src[start-1]
		if isWordByte(prev) {
			return "", start, false
		}
	}
	m := reNamespace.FindStringSubmatchIndex(src[start:])
	if m == nil || m[0] != 0 {
		return "", start, false
	}
	ns := src[start+m[2] : start+m[3]]
	// m[1] is one past the `;` or `{`. Back off by one for block-scoped so
	// the main loop sees the `{`; keep past `;` for file-scoped.
	closer := src[start+m[1]-1]
	if closer == '{' {
		return ns, start + m[1] - 1, true
	}
	return ns, start + m[1], false
}

// matchClassDecl returns (className, endPos) if src[start:] begins a class
// declaration (modulo leading whitespace and modifiers); returns ("", start)
// otherwise. We do a per-position check rather than FindAll because we need
// to interleave class-decl recognition with brace tracking. The regex must
// be anchored at the current position; `\b` would still match interior
// positions, so we explicitly require a non-word character (or start of
// string) immediately before the match.
func matchClassDecl(src string, start int) (string, int) {
	// Require a non-word char or BOS before the modifier/keyword.
	if start > 0 {
		prev := src[start-1]
		if isWordByte(prev) {
			return "", start
		}
	}
	m := reClassDecl.FindStringSubmatchIndex(src[start:])
	if m == nil || m[0] != 0 {
		return "", start
	}
	name := src[start+m[2] : start+m[3]]
	// Skip generic classes — rd.xml type-lookup needs backtick-arity names
	// (e.g. `NdrEmbeddedPointer\`1`) plus per-instantiation `Generic` blocks
	// for full preservation. Emitting the bare name "NdrEmbeddedPointer"
	// makes ILCompiler's RdXmlRootProvider.ProcessTypeDirective fail with
	// "Failed to load type Foo from assembly Bar". The assembly-level
	// Required-All directive on the parent assembly already covers generic
	// types' methods/properties; skipping the per-Type entry just costs a
	// small bit of trim-survival robustness on reflection paths that target
	// a specific generic instantiation. The regex captures only `\w+` for
	// the name, so we peek at the next byte to detect a leading `<`.
	end := start + m[3]
	if end < len(src) && src[end] == '<' {
		return "", start + m[1]
	}
	return name, start + m[1]
}

func isWordByte(b byte) bool {
	return b == '_' || (b >= '0' && b <= '9') || (b >= 'A' && b <= 'Z') || (b >= 'a' && b <= 'z')
}

// stripDebugConditionals blanks out content inside `#if DEBUG … #endif` (or
// `… #else … #endif`) blocks so we don't try to preserve types that aren't
// in the Release-mode IL. Targets only `#if DEBUG` precisely (the bare
// keyword) because the docker build runs `dotnet publish -c Release` with
// DEBUG undefined. Other preprocessor symbols (e.g. NETFRAMEWORK) are
// left untouched; if a class inside such a block isn't actually compiled,
// the resulting "Failed to load type" error gives us a clear signal to
// extend this handler. Line numbers are preserved (lines blanked, not
// removed) so column counts in any downstream error message stay aligned
// with the original source.
//
// Nested #if blocks are not supported — Seatbelt and the other ports we
// target don't use them. If a future codebase does, this function will
// silently mis-handle them; extend then.
func stripDebugConditionals(src string) string {
	// Strip UTF-8 BOM if present — Roslyn-emitted files (and many editors)
	// prepend "\xef\xbb\xbf" which is U+FEFF. strings.TrimSpace does NOT
	// consider U+FEFF whitespace, so without stripping it the BOM ends up
	// glued to the first directive (e.g. "<BOM>#if DEBUG") and HasPrefix
	// fails. Go rejects literal BOMs mid-source, so we use the escape form.
	src = strings.TrimPrefix(src, "\ufeff")
	if !strings.Contains(src, "#if DEBUG") {
		return src
	}
	lines := strings.Split(src, "\n")
	excludeRegion := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "#if "):
			cond := strings.TrimSpace(trimmed[len("#if "):])
			if cond == "DEBUG" {
				excludeRegion = true
			}
			lines[i] = ""
		case strings.HasPrefix(trimmed, "#else"):
			if excludeRegion {
				excludeRegion = false
				lines[i] = ""
				continue
			}
			// Inverse: switching INTO an excluded #else of a non-DEBUG #if.
			// Out of scope for now — leave the directive in place; the body
			// regex will still over-match but at least nothing is mis-blanked.
		case strings.HasPrefix(trimmed, "#endif"):
			excludeRegion = false
			lines[i] = ""
		default:
			if excludeRegion {
				lines[i] = ""
			}
		}
	}
	return strings.Join(lines, "\n")
}

// stripCSharpComments removes // line comments and /* … */ block comments
// from C# source so the regexes don't match commented-out class declarations.
// String literals are blanked (preserved as same-length whitespace) to avoid
// matching `"public class Foo"` literals. Verbatim strings (`@"…"`) and
// escape sequences are honored.
func stripCSharpComments(src string) string {
	out := make([]byte, 0, len(src))
	i := 0
	n := len(src)
	for i < n {
		c := src[i]
		// Block comment
		if c == '/' && i+1 < n && src[i+1] == '*' {
			i += 2
			for i+1 < n && !(src[i] == '*' && src[i+1] == '/') {
				if src[i] == '\n' {
					out = append(out, '\n') // preserve line numbers
				}
				i++
			}
			i += 2
			continue
		}
		// Line comment
		if c == '/' && i+1 < n && src[i+1] == '/' {
			for i < n && src[i] != '\n' {
				i++
			}
			continue
		}
		// Verbatim string @"…" — "" escapes inside
		if c == '@' && i+1 < n && src[i+1] == '"' {
			out = append(out, ' ', ' ')
			i += 2
			for i < n {
				if src[i] == '"' {
					if i+1 < n && src[i+1] == '"' {
						out = append(out, ' ', ' ')
						i += 2
						continue
					}
					out = append(out, ' ')
					i++
					break
				}
				if src[i] == '\n' {
					out = append(out, '\n')
				} else {
					out = append(out, ' ')
				}
				i++
			}
			continue
		}
		// Regular string "…" — \" escapes
		if c == '"' {
			out = append(out, ' ')
			i++
			for i < n && src[i] != '\n' {
				if src[i] == '\\' && i+1 < n {
					out = append(out, ' ', ' ')
					i += 2
					continue
				}
				if src[i] == '"' {
					out = append(out, ' ')
					i++
					break
				}
				out = append(out, ' ')
				i++
			}
			continue
		}
		out = append(out, c)
		i++
	}
	return string(out)
}

func discoverStubAssemblies(srcDir string) ([]string, error) {
	var found []string
	seen := map[string]bool{}

	candidates := []string{
		filepath.Join(srcDir, "stubs"),
		filepath.Join(srcDir, "dotnet", "stubs"),
	}

	for _, root := range candidates {
		if _, err := os.Stat(root); err != nil {
			continue
		}
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(path, ".csproj") {
				return nil
			}
			name := stubAssemblyName(path)
			if name == "" || seen[name] {
				return nil
			}
			seen[name] = true
			found = append(found, name)
			return nil
		})
		if err != nil {
			return found, err
		}
	}
	return found, nil
}

func discoverMainAssembly(srcDir string) string {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return ""
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".csproj") {
			continue
		}
		return stubAssemblyName(filepath.Join(srcDir, e.Name()))
	}
	return ""
}

func stubAssemblyName(csprojPath string) string {
	data, err := os.ReadFile(csprojPath)
	if err == nil {
		const open, close = "<AssemblyName>", "</AssemblyName>"
		if i := strings.Index(string(data), open); i >= 0 {
			rest := string(data[i+len(open):])
			if j := strings.Index(rest, close); j > 0 {
				if name := strings.TrimSpace(rest[:j]); name != "" {
					return name
				}
			}
		}
	}
	base := filepath.Base(csprojPath)
	return strings.TrimSuffix(base, ".csproj")
}
